version: '3.8'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-db
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Your_Password123
      - ACCEPT_EULA=Y
